services:
  iptv-api:
    image: guovern/iptv-api:latest
    container_name: iptv-api
    restart: unless-stopped

    ports:
      - "80:8080"

    volumes:
      - /iptv-api/config:/iptv-api/config
      - /iptv-api/output:/iptv-api/output

    environment:
      PUBLIC_SCHEME: "http"
      # Replace with your public domain or IP
      PUBLIC_DOMAIN: "127.0.0.1"
      PUBLIC_PORT: "80"
      NGINX_HTTP_PORT: "8080"
      CDN_URL: ""
      HTTP_PROXY: ""